spring:
      datasource:
                url: jdbc:postgresql://localhost:5432/marketplace
                driver-class-name: org.postgresql.Driver
                username: postgres
                password: 1234567890
      jpa:
          hibernate.ddl-auto: update

server:
  port: 2612
